# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddDealersDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 17, 381, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dClearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.dClearButton.setObjectName("dClearButton")
        self.gridLayout.addWidget(self.dClearButton, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.TelLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.TelLine.setObjectName("TelLine")
        self.gridLayout.addWidget(self.TelLine, 3, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.FLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.FLine.setObjectName("FLine")
        self.gridLayout.addWidget(self.FLine, 4, 1, 1, 3)
        self.INNLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.INNLine.setObjectName("INNLine")
        self.gridLayout.addWidget(self.INNLine, 1, 1, 1, 3)
        self.SiteLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.SiteLine.setObjectName("SiteLine")
        self.gridLayout.addWidget(self.SiteLine, 2, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.dOKButton = QtWidgets.QPushButton(self.layoutWidget)
        self.dOKButton.setObjectName("dOKButton")
        self.gridLayout.addWidget(self.dOKButton, 5, 3, 1, 1)
        self.NLine = QtWidgets.QLineEdit(self.layoutWidget)
        self.NLine.setObjectName("NLine")
        self.gridLayout.addWidget(self.NLine, 0, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dClearButton.setText(_translate("Dialog", "Clear"))
        self.label_6.setText(_translate("Dialog", "Дата регистрации"))
        self.label.setText(_translate("Dialog", "DATABASE MANAGER"))
        self.label_3.setText(_translate("Dialog", "ИНН"))
        self.label_5.setText(_translate("Dialog", "Телефон"))
        self.label_4.setText(_translate("Dialog", "Сайт"))
        self.dOKButton.setText(_translate("Dialog", "ОК"))
        self.label_2.setText(_translate("Dialog", "Название"))
