# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSupplyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 17, 381, 271))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.amountLine = QtWidgets.QLineEdit(self.widget)
        self.amountLine.setObjectName("amountLine")
        self.gridLayout.addWidget(self.amountLine, 2, 1, 1, 3)
        self.sOKButton = QtWidgets.QPushButton(self.widget)
        self.sOKButton.setObjectName("sOKButton")
        self.gridLayout.addWidget(self.sOKButton, 5, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.dateLine = QtWidgets.QLineEdit(self.widget)
        self.dateLine.setObjectName("dateLine")
        self.gridLayout.addWidget(self.dateLine, 4, 1, 1, 3)
        self.comLine = QtWidgets.QLineEdit(self.widget)
        self.comLine.setObjectName("comLine")
        self.gridLayout.addWidget(self.comLine, 0, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.sClearButton = QtWidgets.QPushButton(self.widget)
        self.sClearButton.setObjectName("sClearButton")
        self.gridLayout.addWidget(self.sClearButton, 5, 2, 1, 1)
        self.typeLine = QtWidgets.QLineEdit(self.widget)
        self.typeLine.setObjectName("typeLine")
        self.gridLayout.addWidget(self.typeLine, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.priceLine = QtWidgets.QLineEdit(self.widget)
        self.priceLine.setObjectName("priceLine")
        self.gridLayout.addWidget(self.priceLine, 3, 1, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sOKButton.setText(_translate("Dialog", "ОК"))
        self.label_4.setText(_translate("Dialog", "Кол-во "))
        self.label_5.setText(_translate("Dialog", "Цена за 1шт."))
        self.label_6.setText(_translate("Dialog", "Дата поставки"))
        self.label.setText(_translate("Dialog", "DATABASE MANAGER"))
        self.sClearButton.setText(_translate("Dialog", "Clear"))
        self.label_2.setText(_translate("Dialog", "Компания"))
        self.label_3.setText(_translate("Dialog", "Название товара"))
