# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteDealers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(393, 303)
        font = QtGui.QFont()
        font.setPointSize(13)
        Dialog.setFont(font)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 379, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.compLineD = QtWidgets.QLineEdit(self.widget)
        self.compLineD.setObjectName("compLineD")
        self.verticalLayout.addWidget(self.compLineD)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DelDClearButton = QtWidgets.QPushButton(self.widget)
        self.DelDClearButton.setObjectName("DelDClearButton")
        self.horizontalLayout.addWidget(self.DelDClearButton)
        self.DelDOKButto = QtWidgets.QPushButton(self.widget)
        self.DelDOKButto.setObjectName("DelDOKButto")
        self.horizontalLayout.addWidget(self.DelDOKButto)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Введите название компании,которую хотите удалить"))
        self.DelDClearButton.setText(_translate("Dialog", "Clear"))
        self.DelDOKButto.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "DATABASE MANAGER"))
