# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Регистрация")
        Dialog.resize(414, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 401, 281))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.regButton = QtWidgets.QPushButton(self.widget)
        self.regButton.setObjectName("regButton")
        self.gridLayout_2.addWidget(self.regButton, 2, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fNameLine = QtWidgets.QLineEdit(self.widget)
        self.fNameLine.setObjectName("fNameLine")
        self.gridLayout.addWidget(self.fNameLine, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lNameLine = QtWidgets.QLineEdit(self.widget)
        self.lNameLine.setObjectName("lNameLine")
        self.gridLayout.addWidget(self.lNameLine, 4, 1, 1, 1)
        self.loginLine = QtWidgets.QLineEdit(self.widget)
        self.loginLine.setObjectName("loginLine")
        self.gridLayout.addWidget(self.loginLine, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.passAgainLine = QtWidgets.QLineEdit(self.widget)
        self.passAgainLine.setObjectName("passAgainLine")
        self.gridLayout.addWidget(self.passAgainLine, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.workLine = QtWidgets.QLineEdit(self.widget)
        self.workLine.setObjectName("workLine")
        self.gridLayout.addWidget(self.workLine, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.passLine = QtWidgets.QLineEdit(self.widget)
        self.passLine.setObjectName("passLine")
        self.gridLayout.addWidget(self.passLine, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setPointSize(38)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Регистрация"))
        self.regButton.setText(_translate("Dialog", "Регистрация"))
        self.label_5.setText(_translate("Dialog", "Фамилия"))
        self.label_2.setText(_translate("Dialog", "Логин"))
        self.label.setText(_translate("Dialog", "Пароль"))
        self.label_4.setText(_translate("Dialog", "Имя"))
        self.label_3.setText(_translate("Dialog", "Повторите пароль"))
        self.label_6.setText(_translate("Dialog", "Должность"))
        self.label_7.setText(_translate("Dialog", "DATABASE MANAGER"))
